"""
========================================================================================
Dobot Magician Lite & Magic Box Controller API (Python / Serial & MicroPython Deployer)
Target Hardware: Dobot Magician Lite + Magic Box Controller
Serial Port: /dev/cu.usbmodem549A30D515392
Storage Mount: /Volumes/NO NAME 1
========================================================================================
"""

import os
import sys
import time
import shutil
import serial
import serial.tools.list_ports

def find_magic_box_mount():
    for name in ["/Volumes/NO NAME", "/Volumes/NO NAME 1"]:
        if os.path.exists(name) and os.path.exists(os.path.join(name, "System")):
            return name
    return "/Volumes/NO NAME"

MAGIC_BOX_MOUNT_POINT = find_magic_box_mount()
DEFAULT_SERIAL_PORT = "/dev/cu.usbmodem549A30D515392"

class DobotMagicBoxManager:
    def __init__(self, mount_point=MAGIC_BOX_MOUNT_POINT, serial_port=DEFAULT_SERIAL_PORT):
        self.mount_point = mount_point
        self.serial_port = serial_port

    def is_connected(self):
        """Check if Dobot Magic Box is connected via Mass Storage or Serial Port"""
        storage_found = os.path.exists(self.mount_point)
        serial_found = os.path.exists(self.serial_port)
        return storage_found, serial_found

    def list_installed_scripts(self):
        """List all Python scripts currently stored on the Magic Box"""
        scripts_dir = os.path.join(self.mount_point, "Script")
        if not os.path.exists(scripts_dir):
            return []
        return [f for f in os.listdir(scripts_dir) if f.endswith(".py")]

    def deploy_script_to_magic_box(self, script_code: str, script_name: str = "CustomTask.py", set_as_default: bool = True):
        """Write a new MicroPython script directly to Magic Box flash storage"""
        if not os.path.exists(self.mount_point):
            raise FileNotFoundError(f"Magic Box flash storage not found at {self.mount_point}. Ensure USB is connected.")
        
        script_path = os.path.join(self.mount_point, "Script", script_name)
        with open(script_path, "w") as f:
            f.write(script_code)
        print(f"[OK] Script saved to Magic Box: {script_path}")

        if set_as_default:
            # Update main.py to execute this script
            main_py_path = os.path.join(self.mount_point, "System", "main.py")
            main_code = f"""# Auto-generated by DobotManager
import _thread
import os
import mb
import mgo
import mgl
import dType
import pyb
import rtt
import time

api = 0
def main():
    try:
        exec(open('Script/{script_name}').read())
    except Exception as e:
        rtt.print('Script Error {{}}'.format(e))
        dType.PrintInfo(api, str('Err: {{}}'.format(e)))

_thread.start_new_thread(main, ())
"""
            with open(main_py_path, "w") as f:
                f.write(main_code)
            print(f"[OK] {script_name} configured as default boot script.")

    def generate_pick_and_place_script(self, pickup_xyzr=(300.0, -100.0, -20.0, 0.0), 
                                        dropoff_xyzr=(300.0, 100.0, -20.0, 0.0), 
                                        effector="suction", repeat=3):
        """
        Generates ready-to-run MicroPython script utilizing the onboard dType API
        effector: 'suction' or 'gripper'
        """
        is_gripper = 1 if effector == "gripper" else 0
        is_suction = 1 if effector == "suction" else 0

        code = f"""# MicroPython Standalone Script for Dobot Magician Lite
# Auto-generated for Kerala State Sasthramela
import dType
import time

api = 0
dType.SetQueuedCmdClear(api)
dType.SetQueuedCmdStopExec(api)
dType.SetQueuedCmdStartExec(api)

# 1. Homing & Speed Configuration
dType.SetHOMECmdEx(api, 0, 1)
dType.SetArmSpeedRatio(api, 1, 40, 1)
dType.SetPTPJumpParams(api, 25.0, 100.0, 1)

# Set End Effector Type (1: Gripper, 2: Suction Cup)
effector_type = {1 if is_gripper else 2}
dType.SetEndEffectorTypeEx(api, effector_type, 1)

# Safe Transit Height
SAFE_Z = 30.0

for cycle in range({repeat}):
    dType.PrintInfo(api, "Cycle " + str(cycle + 1))
    
    # Move to Hover above Pickup Location
    dType.SetPTPCmdEx(api, 1, {pickup_xyzr[0]}, {pickup_xyzr[1]}, SAFE_Z, {pickup_xyzr[3]}, 1)
    
    # Lower to Pickup Position
    dType.SetPTPCmdEx(api, 1, {pickup_xyzr[0]}, {pickup_xyzr[1]}, {pickup_xyzr[2]}, {pickup_xyzr[3]}, 1)
    
    # Activate Gripper / Vacuum Suction
    {'dType.SetEndEffectorGripperEx(api, 1, 1)' if is_gripper else 'dType.SetEndEffectorSuctionCupEx(api, 1, 1, 1)'}
    dType.dSleep(800)
    
    # Lift to Safe Transit Height
    dType.SetPTPCmdEx(api, 1, {pickup_xyzr[0]}, {pickup_xyzr[1]}, SAFE_Z, {pickup_xyzr[3]}, 1)
    
    # Transit to Dropoff Location (Hover)
    dType.SetPTPCmdEx(api, 1, {dropoff_xyzr[0]}, {dropoff_xyzr[1]}, SAFE_Z, {dropoff_xyzr[3]}, 1)
    
    # Lower to Place Position
    dType.SetPTPCmdEx(api, 1, {dropoff_xyzr[0]}, {dropoff_xyzr[1]}, {dropoff_xyzr[2]}, {dropoff_xyzr[3]}, 1)
    
    # Release Object
    {'dType.SetEndEffectorGripperEx(api, 1, 0)' if is_gripper else 'dType.SetEndEffectorSuctionCupEx(api, 0, 0, 1)'}
    dType.dSleep(600)
    
    # Return to Safe Hover
    dType.SetPTPCmdEx(api, 1, {dropoff_xyzr[0]}, {dropoff_xyzr[1]}, SAFE_Z, {dropoff_xyzr[3]}, 1)

# Return to Home / Standby Position
dType.SetPTPCmdEx(api, 1, 240.0, 0.0, 50.0, 0.0, 1)
dType.PrintInfo(api, "Task Completed Successfully!")
"""
        return code

if __name__ == "__main__":
    manager = DobotMagicBoxManager()
    storage_ok, serial_ok = manager.is_connected()
    
    print("=" * 60)
    print(" DOBOT MAGICIAN LITE / MAGIC BOX DIAGNOSTICS")
    print("=" * 60)
    print(f"Flash Storage (/Volumes/NO NAME 1) : {'[DETECTED]' if storage_ok else '[NOT FOUND]'}")
    print(f"Serial Port ({DEFAULT_SERIAL_PORT})  : {'[DETECTED]' if serial_ok else '[NOT FOUND]'}")
    
    if storage_ok:
        scripts = manager.list_installed_scripts()
        print(f"\nInstalled Scripts on Magic Box:")
        for s in scripts:
            print(f" - {s}")
            
    print("=" * 60)
