[platformio]
src_dir = .

[env:uno]
platform = atmelavr
board = uno
framework = arduino
upload_port = /dev/cu.wchusbserial110
monitor_speed = 9600

[env:nano]
platform = atmelavr
board = nanoatmega328
framework = arduino
upload_port = /dev/cu.wchusbserial110
monitor_speed = 9600

[env:nano_new]
platform = atmelavr
board = nanoatmega328new
framework = arduino
upload_port = /dev/cu.wchusbserial110
monitor_speed = 9600
